# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
# https://github.com/craigcitro/r-travis/wiki

os:
  - linux
  - osx

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  provider: releases
  api_key:
    secure: Fy9jGwyWhp9ir2Zil0848B1o0IUC5dH4PRB/v7V66h0GqiOtPyf1JkBQySUc67wTqDGgEF0+K5J06q25Dcr6vXWV6b12gUw5RzoYbsp7wyq3cxf7G+bL2RYJJ3Cs/cxfUhAQixl4UgsWS2avVou1nMXWB679p8mQRksb9D/AbVI=
  file_glob: true
  file: FLCore_*.*
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: flr/FLCore
    branch: master
